version: "3.9"

services:
  # ------------------- MongoDB -------------------
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  # ------------------- Backend -------------------
  backend:
    build: ./WebScraping/Backend
    container_name: backend
    restart: always
    env_file: .env
    ports:
      - "${BACKEND_PORT}:3000"  # Puerto interno del contenedor Node.js es 3000
    depends_on:
      - mongodb

  # ------------------- Frontend -------------------
  frontend:
    build: ./WebScraping/Frontend
    container_name: frontend
    restart: always
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:80"   # Nginx escucha en 80 dentro del contenedor
    depends_on:
      - backend
    # No necesitamos montar nginx sobre la imagen de build de React
    # porque el Dockerfile ya incluye Nginx
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  # ------------------- VNC -------------------
  vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: vnc
    restart: always
    environment:
      - USER=ubuntu
      - PASSWORD=1234
    ports:
      - "${VNC_PORT}:6080"
    volumes:
      - ./vnc_data:/home/ubuntu
    shm_size: "2gb"

volumes:
  mongo_data:
  vnc_data:
